<?php
$customers = $this->getOrderCustomer();
?>
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Billing Address
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-8">
                        <?php foreach ($customers as $customer){ ?>
                            <div class="form-group">
                                <label>First Name *</label>
                                <input type="text" class="form-control" value="<?php echo $customer->getData('firstname') ?>" name="firstname">
                            </div>
                            <div class="form-group">
                                <label>Last Name *</label>
                                <input type="text" class="form-control" value="<?php echo $customer->getData('lastname') ?>" name="lastname">
                            </div>
                            <div class="form-group">
                                <label>City *</label>
                                <input type="text" class="form-control" value="<?php echo $customer->getData('billing_city') ?>" name="billing_city">
                            </div>
                            <div class="form-group">
                                <label>Country *</label>
                                <input type="text" class="form-control" value="<?php echo $customer->getData('billing_region') ?>" name="billing_region">
                            </div>
                            <div class="form-group">
                                <label>Zip/Postal Code *</label>
                                <input type="text" class="form-control" value="<?php echo $customer->getData('billing_postcode') ?>" name="billing_postcode">
                            </div>
                            <div class="form-group">
                                <label>Telephone *</label>
                                <input type="text" class="form-control" value="<?php echo $customer->getData('billing_telephone') ?>" name="billing_telephone">
                            </div>

                        <?php } ?>
                    </div>
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
