<?php
$dataPost = $this->getPostData();
?>
<div class="col-lg-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            Billing Address
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-8">
                        <div class="form-group">
                            <label>First Name *</label>
                            <input type="text" class="form-control" value="<?php echo $dataPost['firstname'] ?>" name="firstname" readonly>
                        </div>
                        <div class="form-group">
                            <label>Last Name *</label>
                            <input type="text" class="form-control" value="<?php echo $dataPost['lastname'] ?>" name="lastname" readonly>
                        </div>
                        <div class="form-group">
                            <label>City *</label>
                            <input type="text" class="form-control" value="<?php echo $dataPost['billing_city'] ?>" name="billing_city" readonly>
                        </div>
                        <div class="form-group">
                            <label>Country *</label>
                            <input type="text" class="form-control" value="<?php echo $dataPost['billing_region'] ?>" name="billing_region" readonly>
                        </div>
                        <div class="form-group">
                            <label>Zip/Postal Code *</label>
                            <input type="text" class="form-control" value="<?php echo $dataPost['billing_postcode'] ?>" name="billing_postcode" readonly >
                        </div>
                        <div class="form-group">
                            <label>Telephone *</label>
                            <input type="text" class="form-control" value="<?php echo $dataPost['billing_telephone'] ?>" name="billing_telephone" readonly>
                        </div>

                </div>
            </div>
            <!-- /.row (nested) -->
        </div>
        <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
</div>
<!-- /.col-lg-12 -->
