<?php
$customers = $this->getOrderCustomer();

$countries = $this->getCountryId();

foreach ($customers as $customer) {
    $regions = $this->getRegionId($customer->getData('billing_country_id'));
}
?>
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Billing Address
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-8">
                        <?php foreach ($customers as $customer){ ?>
                            <div class="form-group">
                                <label>First Name *</label>
                                <input type="text" class="form-control" value="<?php echo $customer->getData('firstname') ?>" name="firstname">
                            </div>
                            <div class="form-group">
                                <label>Last Name *</label>
                                <input type="text" class="form-control" value="<?php echo $customer->getData('lastname') ?>" name="lastname">
                            </div>
                            <div class="form-group">
                                <label>Street *</label>
                                <input type="text" class="form-control" value="<?php echo $customer->getData('billing_street') ?>" name="billing_street">
                            </div>
                            <div class="form-group">
                                <label>City *</label>
                                <input type="text" class="form-control" value="<?php echo $customer->getData('billing_city') ?>" name="billing_city">
                            </div>
                            <div class="form-group">
                                <label>Country *</label>
                                <select class="form-control" name="billing_country_id" id="billing_country_id">
                                    <?php
                                    foreach ($countries as $country){ ?>
                                        <?php if ($customer->getData('billing_country_id') == $country['value']) { ?>
                                            <option value="<?php echo $country['value'] ?>" selected><?php echo $country['label'] ?></option>
                                        <?php } else { ?>
                                            <option value="<?php echo $country['value'] ?>"><?php echo $country['label'] ?></option>
                                        <?php } ?>
                                    <?php }
                                    ?>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>State/Province *</label>
                                <select class="form-control" name="billing_region" id="billing_region">
                                    <?php
                                    foreach ($regions as $region){ ?>
                                        <?php if ($customer->getData('billing_region') == $region['value']) { ?>
                                            <option value="<?php echo $region['value'] ?>" selected><?php echo $region['label'] ?></option>
                                        <?php } else { ?>
                                            <option value="<?php echo $region['value'] ?>"><?php echo $region['label'] ?></option>
                                        <?php } ?>
                                    <?php }
                                    ?>
                                </select>
                            </div>

                            <div class="form-group">
                                <label>Zip/Postal Code *</label>
                                <input type="text" class="form-control" value="<?php echo $customer->getData('billing_postcode') ?>" name="billing_postcode">
                            </div>
                            <div class="form-group">
                                <label>Telephone *</label>
                                <input type="text" class="form-control" value="<?php echo $customer->getData('billing_telephone') ?>" name="billing_telephone">
                            </div>
                        <?php } ?>
                    </div>
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->