<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $customers = $this->getCollection(); ?>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4><?php echo $this->__("Customer Order List") ?></h4>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">
<!--                    --><?php //echo $this->getPagerHtml(); ?>
<!--                    --><?php //if($customers->getSize()): ?>
                    <table class="table table-striped table-bordered table-hover" id="customers_info">
                        <thead>
                        <tr>
                            <th><?php echo $this->__("ID") ?></th>
                            <th><?php echo $this->__("Name") ?></th>
                            <th><?php echo $this->__("Email") ?></th>
                            <th><?php echo $this->__("Telephone") ?></th>
                            <th><?php echo $this->__("Action") ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $_odd = ''; ?>
                        <?php foreach ($customers as $customer){ ?>
                        <tr class="odd gradeX">
                            <td><?php echo $customer->getData('entity_id') ?></td>
                            <td><?php echo $customer->getData('name') ?></td>
                            <td><?php echo $customer->getData('email') ?></td>
                            <td class="center"><?php echo $customer->getData('billing_telephone') ?></td>
                            <td class="center"><a href="<?php echo Mage::helper("adminhtml")->getUrl('*/*/product', array('id'=> $customer->getData('entity_id'))); ?>" target="_blank" class="report"><?php echo $this->__("Create Order") ?></a></td>
                        </tr>
                        <?php } ?>
                        </tbody>
                    </table>
<!--                    --><?php //echo $this->getPagerHtml(); ?>
<!--                    --><?php //else: ?>
<!--                        <p>--><?php //echo $this->__('The collection is empty.'); ?><!--</p>-->
<!--                    --><?php //endif ?>

                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<script type="text/javascript">
    $(document).ready(function(){
        $('#customers_info').DataTable();
    });
</script>