<form id="edit_form" action="<?php echo $this->getSaveUrl() ?>" method="post" aria-readonly="true">
    <?php echo $this->getBlockHtml('formkey') ?>
    <div class="billing_address">
        <?php echo $this->getChildHtml('test.billingFixed') ?>
    </div>
    <div class="shipping_address">
        <?php echo $this->getChildHtml('test.shippingFixed') ?>
    </div>
    <div class="order">
        <?php echo $this->getChildHtml('test.order') ?>
    </div>
    <div class="payment">
        <?php echo $this->getChildHtml('test.payment') ?>
    </div>
    <div class="shipment">
        <?php echo $this->getChildHtml('test.shipment') ?>
    </div>
<!--    <div class="total_order">-->
<!--        --><?php //echo $this->getChildHtml('test.total') ?>
<!--    </div>-->
    <button class="btn btn-default" type="submit" style="float: right;">SUBMIT</button>
</form>
<script>
    form.items.each(function(f){
        f.el.dom.readOnly = true;
    });
</script>
