<?php $products = $this->getProductOrder(); ?>
<?php $customers = $this->getOrderCustomer(); ?>
<?php $qtyOrders = $this->getQtyOrder(); ?>
<?php //foreach ($qtyOrders as $qtyOrder) {
//    Zend_Debug::dump($qtyOrder['qty']);
//    die();
//} ?>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4><?php echo $this->__("Order Products List") ?></h4>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">
                        <table class="table table-striped table-bordered table-hover" id="products_info">
                            <thead>
                            <tr>
                                <th><?php echo $this->__("ID") ?></th>
                                <th><?php echo $this->__("Name") ?></th>
                                <th><?php echo $this->__("Type") ?></th>
                                <th><?php echo $this->__("SKU") ?></th>
                                <th><?php echo $this->__("Price") ?></th>
                                <th><?php echo $this->__("Quantity") ?></th>
                                <th><?php echo $this->__("Cash") ?></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php $_odd = ''; ?>
                            <?php foreach ($products as $product){ ?>
                                <tr class="odd gradeX">
                                    <td><input name="productId[]" type="text" style="width: 30px;" value="<?php echo $product->entity_id ?>" readonly></td>
                                    <td><?php echo $product->name ?></td>
                                    <td><?php echo $product->type_id ?></td>
                                    <td class="center"><?php echo $product->sku ?></td>
                                    <td class="center"><?php echo $product->price ?></td>
                                    <?php foreach ($qtyOrders as $qtyOrder) { ?>
                                        <?php if ($qtyOrder['product_id'] == $product->entity_id) { ?>
                                            <td class="center"><input name="productQty[]" type="text" style="width: 30px;" value="<?php echo $qtyOrder['qty'] ?>" readonly></td>
                                            <td class="center"><?php echo $qtyOrder['qty']*$product->price ?>,000</td>
                                        <?php } ?>
                                    <?php }?>
                                </tr>
                            <?php }?>
                            </tbody>
                        </table>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<script type="text/javascript">
    $(document).ready(function(){
        $('#products_info').DataTable();
    });
</script>