<?php
//$collection = $this->getProduct();
////foreach ($collection as $product) {
////    Zend_Debug::dump($product);
////    die();
////echo $product->getName(); //get name
////echo (float) $product->getPrice(); //get price as cast to float
////echo $product->getDescription(); //get description
////echo $product->getShortDescription(); //get short description
////echo $product->getTypeId(); //get product type
////echo $product->getStatus(); //get product status
////
////// getCategoryIds(); returns an array of category IDs associated with the product
////foreach ($product->getCategoryIds() as $category_id) {
////    $category = Mage::getModel('catalog/category')->load($category_id);
////    echo $category->getName();
////    echo $category->getParentCategory()->getName(); // get parent of category
////}
////    echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).
////        'catalog/product'.$product->getImage();
////    echo $product->getSpecialPrice();
////    echo $product->getProductUrl();  //gets the product url
////    echo '<br />';
////    die();
////}
////die();
//?>
<?php $products = $this->getProduct(); ?>
<?php $customers = $this->getOrderCustomer(); ?>
<?php foreach ($customers as $customer){ ?>
<h3>Select Product to Order for <b><?php echo $customer->getData('name') ?></b></h3>
<?php } ?>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4><?php echo $this->__("Products List") ?></h4>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">

                    <table class="table table-striped table-bordered table-hover" id="products_info">
                        <thead>
                        <tr>
                            <th><?php echo $this->__("ID") ?></th>
                            <th><?php echo $this->__("Name") ?></th>
                            <th><?php echo $this->__("Type") ?></th>
                            <th><?php echo $this->__("SKU") ?></th>
                            <th><?php echo $this->__("Price") ?></th>
                            <th><?php echo $this->__("Quantity") ?></th>
                            <th><?php echo $this->__("Select") ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $_odd = ''; ?>
                        <?php foreach ($products as $product){ ?>
                            <tr class="odd gradeX">
                                <td><?php echo $product->entity_id ?></td>
                                <td><?php echo $product->name ?></td>
                                <td><?php echo $product->type_id ?></td>
                                <td class="center"><?php echo $product->sku ?></td>
                                <td class="center"><?php echo $product->price ?></td>
                                <td class="center"><input name="productAddQty[]" type="text" style="width: 50px;"></td>
                                <td class="center"><input name="productAddId[]" type="checkbox" value="<?php echo $product->entity_id ?>"></td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<script type="text/javascript">
    $(document).ready(function(){
        $('#products_info').DataTable();
    });
</script>