<h2>Search Product</h2>
<form role="form" id="edit_form" action="<?php echo Mage::helper("adminhtml")->getUrl('*/*/search'); ?>" method="post" enctype="multipart/form-data">
    <?php echo $this->getBlockHtml('formkey')?>
    <div class="input-group custom-search-form">
        <input type="text" name="search" class="form-control" placeholder="Search Product..." required>
        <button class="btn btn-default" type="submit">Search
        </button>
    </div>
</form>
