<?php
$dataPost = $this->getPostData();
?>
<div class="col-lg-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            Shipping Address
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-8" >
                        <div class="form-group">
                            <label>First Name *</label>
                            <input type="text" class="form-control" value="<?php echo $dataPost['shipping_firstname'] ?>" name="shipping_firstname" readonly>
                        </div>
                        <div class="form-group">
                            <label>Last Name *</label>
                            <input type="text" class="form-control" value="<?php echo $dataPost['shipping_lastname'] ?>" name="shipping_lastname" readonly>
                        </div>
                        <div class="form-group">
                            <label>City *</label>
                            <input type="text" class="form-control" value="<?php echo $dataPost['shipping_city'] ?>" name="shipping_city" readonly>
                        </div>
                        <div class="form-group">
                            <label>Country *</label>
                            <input type="text" class="form-control" value="<?php echo $dataPost['shipping_region'] ?>" name="shipping_region" readonly>
                        </div>
                        <div class="form-group">
                            <label>Zip/Postal Code *</label>
                            <input type="text" class="form-control" value="<?php echo $dataPost['shipping_postcode'] ?>" name="shipping_postcode" readonly>
                        </div>
                        <div class="form-group">
                            <label>Telephone *</label>
                            <input type="text" class="form-control" value="<?php echo $dataPost['shipping_telephone'] ?>" name="shipping_telephone" readonly>
                        </div>
                </div>
            </div>
            <!-- /.row (nested) -->
        </div>
        <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
</div>
<!-- /.col-lg-12 -->
