<?php
$shipmentMethods = $this->getShipmentMethod();
?>

    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4><?php echo $this->__("Shipment Method") ?></h4>
            </div>
            <button>Get Shipment Method</button>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">

                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->